version: '3.9'

services:
  db:
    image: postgres:15
    container_name: delivery_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: evibul29
      POSTGRES_DB: delivery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: